app:
  name: "musannif"
  sqlite_directory: "/var/db/musannif/"
  log_directory: "/var/logs/musannif/"
  environment: "dev"
server:
  host: "localhost"
  port: 8242
secrets:
  JWT_ACCESS_SECRET: ""
  JWT_REFRESH_SECRET: ""
