name: basic build & test

on:
  workflow_dispatch:
  push:
    paths:
      - 'cmd/**'
      - 'internal/**'
  pull_request:
    paths:
      - 'cmd/**'
      - 'internal/**'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Build
      run: make build-linux-amd64

    - name: Test
      run: go test -v ./...
